[package]
name = "altpollution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.0"
pms-7003 = "0.1.0"
prost = "0.12.3"
prost-types = "0.12.3"
serde_json = "1.0.114"
serial2 = "0.2.20"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
